services:
  - type: web
    name: travo-backend
    env: docker
    region: singapore
    buildCommand: docker build -t travo-backend ./backend
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    plan: free
    branch: main 