services:
  - type: web
    name: travo-backend
    env: docker
    region: singapore
    rootDir: backend
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t travo-backend .
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://axra2025:Frf8uuuBOGRuqg1I@cluster0.trnjnbm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: LOG_LEVEL
        value: "info"
      - key: JWT_EXPIRATION
        value: "7d"
    healthCheckPath: /api/health
    plan: free
    branch: main 