services:
  - type: web
    name: travo-backend
    env: docker
    region: singapore
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    plan: free
    branch: main 