name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Create test env file
      run: |
        echo "MONGODB_URI=mongodb://localhost:27017/test" > .env
        echo "JWT_SECRET=test-secret" >> .env
        echo "NODE_ENV=test" >> .env
        echo "PORT=5000" >> .env
    
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm test
      env:
        CI: true
        NODE_ENV: test

    - name: Build Docker image
      run: docker build -t travo-backend . 