name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Install dependencies
      run: npm install

    - name: Create test setup
      run: |
        echo "module.exports = {};" > jest.setup.js

    - name: Create basic test
      run: |
        mkdir -p src/__tests__
        echo "describe('Basic Test', () => {
          it('should pass', () => {
            expect(true).toBe(true);
          });
        });" > src/__tests__/basic.test.js

    - name: Run tests
      run: npm test
      env:
        CI: true 