name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/ci-tests

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: './frontend/ci-tests/package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Create test environment
      run: |
        echo "REACT_APP_API_URL=http://localhost:5000" > .env.test
        echo "NODE_ENV=test" >> .env.test

    - name: Run tests
      run: npm test
      env:
        CI: true
        NODE_ENV: test 