name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint || echo "No linting configured"

    - name: Run tests
      run: npm test || echo "No tests configured"
      env:
        CI: true

    - name: Build Expo web
      run: expo build:web || echo "Web build not configured"

    - name: Build Android
      run: expo build:android || echo "Android build not configured"
      if: github.ref == 'refs/heads/main' 