name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: './frontend/package-lock.json'

    - name: Install dependencies
      run: |
        npm install -g expo-cli
        npm ci

    - name: Setup Jest config
      run: |
        echo "{
          \"preset\": \"jest-expo\",
          \"transformIgnorePatterns\": [
            \"node_modules/(?!((jest-)?react-native|@react-native(-community)?)|expo(nent)?|@expo(nent)?/.*|@expo-google-fonts/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base|react-native-svg)\"
          ],
          \"setupFiles\": [
            \"<rootDir>/jest.setup.js\"
          ]
        }" > jest.config.json

    - name: Create Jest setup file
      run: |
        echo "jest.mock('expo-font');
        jest.mock('expo-asset');
        jest.mock('@react-native-async-storage/async-storage', () =>
          require('@react-native-async-storage/async-storage/jest/async-storage-mock')
        );" > jest.setup.js

    - name: Run tests
      run: npm test
      env:
        CI: true 